// models/user.rs — User data structures
//
// This file defines what a "User" looks like in our system.
// We have different structs for different purposes:
//
// User          — matches the database table exactly
// RegisterRequest — what the client sends to register
// LoginRequest  — what the client sends to login
// AuthResponse  — what we send back after login/register
// UserResponse  — safe user data we can send to clients

use serde::{Deserialize, Serialize};
use uuid::Uuid;

// User — mirrors the users table in the database
// sqlx::FromRow lets sqlx automatically map a database row into this struct
// When we do SELECT * FROM users, sqlx fills in each field automatically
#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct User {
    pub id: Uuid,              // unique ID, generated by Postgres
    pub email: String,         // user's email address
    pub password_hash: String, // hashed password — NEVER store plain text
    pub full_name: String,     // user's full name
    pub is_active: bool,       // false means the account is disabled
}

// RegisterRequest — the JSON body the client sends to POST /auth/register
// Deserialize lets axum automatically parse the JSON into this struct
#[derive(Debug, Deserialize)]
pub struct RegisterRequest {
    pub email: String,
    pub password: String, // plain text — we hash it before storing
    pub full_name: String,
}

// LoginRequest — the JSON body the client sends to POST /auth/login
#[derive(Debug, Deserialize)]
pub struct LoginRequest {
    pub email: String,
    pub password: String, // plain text — we verify it against the hash
}

// AuthResponse — what we send back after successful login or register
// Contains the JWT token and basic user info
#[derive(Debug, Serialize)]
pub struct AuthResponse {
    pub access_token: String, // the JWT token the client must send on future requests
    pub token_type: String,   // always "Bearer" — tells client how to send the token
    pub user: UserResponse,   // safe user data (no password hash!)
}

// UserResponse — user data safe to send to the client
// We NEVER include password_hash in responses
#[derive(Debug, Serialize)]
pub struct UserResponse {
    pub id: Uuid,
    pub email: String,
    pub full_name: String,
}

// From<User> for UserResponse — converts a User into a UserResponse
// This lets us write: UserResponse::from(user)
// It just copies the safe fields and leaves out password_hash
impl From<User> for UserResponse {
    fn from(user: User) -> Self {
        Self {
            id: user.id,
            email: user.email,
            full_name: user.full_name,
        }
    }
}
